CREATE TABLE IF NOT EXISTS users (
	user_id SERIAL NOT NULL PRIMARY KEY
	, username VARCHAR (255) NOT NULL
	, age INTEGER
	, email VARCHAR (255) NOT NULL
	, password VARCHAR (255) NOT NULL
	, auth VARCHAR (255) NOT NULL
	, created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
	, updated_at TIMESTAMPTZ DEFAULT NULL
	, deleted_at TIMESTAMPTZ DEFAULT NULL
);
